peliculas=[{
            "titulo"        : "La Patagonia rebelde",
            "director"      : "Héctor Olivera",
            "year"          : 1974,
            "protagonistas"	: ["Héctor Alterio","Luis Brandoni","Federico Luppi","Pepe Soriano","Osvaldo Terranova","José María Gutiérrez","Pedro Aleandro Tacholas"],
            "portada"       : "/static/La-patagonia-rebelde.jpg",
            "codigo"        : 1001},
           {"titulo"        : "La tregua",
            "director"      : "Sergio Renán",
            "year"          : 1974,
            "protagonistas" : ["Héctor Alterio", "Ana María Picchio","Oscar Martinez","Norma Aleandro"],
            "portada"       : "/static/La-tregua.jpg",
            "codigo"        : 1002},
            {"titulo"       : "Camila",
            "director"      : "María Luisa Bemberg",
            "year"          : 1984,
            "protagonistas" : ["Héctor Alterio", "Susú Pecoraro","Imanol Arias"],
            "portada"       : "/static/Camila.jpg",
            "codigo"        : 1003},
            {"titulo"       : "Esperando la carroza",
            "director"      : "Alejandro Doria",
            "year"          : 1985,
            "protagonistas" : ["Luis Brandoni","China Zorrilla","Antonio Gasalla","Betiana Blum","Juan Manuel Tenuta",
                               "Andrea Tenuta","Darío Grandinetti","Cecilia Rossetto","Enrique Pinti","Angelita Pardo","Clotilde Borella","Pina Criscuolo",
                               "Juan Acosta","Mónica Alessandría","José Andrada","Gofredo Colombo","Julio de Grazia","Mónica Villa",
                               "Lidia Catalano","Cristina Fridman","Miguel Ángel Porro"],
            "portada"       : "/static/Carroza.jpg",
            "codigo"        : 1004},
            {"titulo"       : "Nueve Reinas",
            "director"      : "Fabián Bielinsky",
            "year"          : 2000,
            "protagonistas" : ["Ricardo Darín","Gastón Pauls","Leticia Brédice","Tomás Fonzi","Graciela Tenenbaum",
                               "Oscar Núñez",  "Alejandro Awada","Elsa Berenguer","Roly Serrano"],
            "portada"       : "/static/Nueve.jpg",
            "codigo"        :1005},
            {"titulo"       : "El hijo de la novia",
            "director"      : "Juan José Campanella",
            "year"          : 2001,
            "protagonistas"	: ["Ricardo Darín","Héctor Alterio","Norma Aleandro","Natalia Verbeke","Eduardo Blanco"],
            "portada"       : "/static/Novia.jpg",
            "codigo"        : 1006},
            {"titulo"       : "Historias mínimas",
            "director"      : "Carlos Sorín",
            "year"          : 2002,
            "protagonistas"	: ["Javier Lombardo","Antonio Benedictti","Javiera Bravo"],
            "portada"       : "/static/Historia.jpg",
            "codigo"        : 1007},
            {"titulo"       : "Tiempo de valientes",
            "director"      : "Damián Szifron",
            "year"          : 2005,
            "protagonistas"	: ["Luis Luque","Diego Peretti"],
            "portada"       : "/static/valientes.jpg",
            "codigo"        : 1008},
            {"titulo"       : "El secreto de sus ojos",
            "director"      : "Juan José Campanella",
            "year"          : 2009,
            "protagonistas"	: ["Ricardo Darín","Soledad Villamil","Pablo Rago","Javier Godino","Guillermo Francella"],
            "portada"       : "/static/secreto.jpg",
            "codigo"        : 1009},
            {"titulo"       : "Relatos Salvajes",
            "director"      : "Damián Szifron",
            "year"          : 2014,
            "protagonistas"	: ["Ricardo Darín","Oscar Martínez","Leonardo Sbaraglia","Érica Rivas","Rita Cortese","Julieta Zylberberg","Darío Grandinetti"],
            "portada"       : "/static/relato.jpg",
            "codigo"        : 1010}]